dependencies:
  flutter:
    sdk: flutter

  zego_plugin_adapter: ^2.13.9

  zego_express_engine:
    git:
      url: https://github.com/Robsnodgrass/flutter_zego_patch.git

  zego_zpns: ^2.6.0+3
  zego_callkit: ^1.0.0+4

  device_info_plus: ^11.3.0
  encrypt: ^5.0.3
  permission_handler: ^11.3.1
  flutter_logs: ^2.2.1
  native_device_orientation: ^2.0.3
  wakelock_plus: ^1.2.10
  cached_network_image: ^3.3.0
  file_picker: ^10.1.2
  path: ^1.8.3
  plugin_platform_interface: ^2.1.8
  visibility_detector: ^0.4.0+2
  connectivity_plus: ^6.1.0
